# Use an official Node.js runtime as a parent image
FROM node:23
RUN npm install -g npm@11.2.0
# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install --force

# Copy the rest of the application
COPY ./public ./public
COPY ./src ./src

ARG IP_AND_PORT
ENV REACT_APP_DATABASE_IP_AND_PORT=${IP_AND_PORT}

# Build the app for production
RUN npm run build

# Install serve and serve the app
RUN npm install -g serve
CMD ["serve", "-s", "build"]

# Expose port
EXPOSE 3000